// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDg3TMq4DOdVTnU0Kw2Og3PDqqmTl8e6k',
    appId: '1:119997886577:web:7561f990fe8b48603eebd0',
    messagingSenderId: '119997886577',
    projectId: 'socialtype-b8cec',
    authDomain: 'socialtype-b8cec.firebaseapp.com',
    storageBucket: 'socialtype-b8cec.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHzvkzQjbg00LBTOgFX9fdEnQJxPMirIs',
    appId: '1:119997886577:android:1f2f37cb8adc366a3eebd0',
    messagingSenderId: '119997886577',
    projectId: 'socialtype-b8cec',
    storageBucket: 'socialtype-b8cec.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD71qKqHf3NvHG3MT3ZsMO65DkLWvQNodc',
    appId: '1:119997886577:ios:b2fd49368f57c5093eebd0',
    messagingSenderId: '119997886577',
    projectId: 'socialtype-b8cec',
    storageBucket: 'socialtype-b8cec.appspot.com',
    iosBundleId: 'com.example.socialType',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD71qKqHf3NvHG3MT3ZsMO65DkLWvQNodc',
    appId: '1:119997886577:ios:42dd45ae240ac6de3eebd0',
    messagingSenderId: '119997886577',
    projectId: 'socialtype-b8cec',
    storageBucket: 'socialtype-b8cec.appspot.com',
    iosBundleId: 'com.example.socialType.RunnerTests',
  );
}
